version: '3.2'

networks:
  crv_prod_network:
    driver: bridge

services:
  db-prod:
    container_name: mysql-prod
    image: mysql:5.7.17
    env_file:
      - ./.env
    volumes:
      - ./volumes/mysql/prod/database:/var/lib/mysql
      - ./volumes/mysql/prod/conf:/etc/mysql/conf.d
    networks:
      crv_prod_network:
        aliases:
          - mysql
    ports:
      - "3306:3306"

  app-prod:
    container_name: symfony-app-prod
    build:
      context: ../
      dockerfile: ./Docker/php/prod/Dockerfile
      args:
        env: prod

    volumes:
      - app_data:/app:rw
      - ./volumes/log/prod/App:/app/App/var/logs
      - ./volumes/cache/prod/App:/app/App/var/cache
      - ./volumes/log/prod/CompositeUi:/app/CompositeUi/var/log
      - ./volumes/cache/prod/CompositeUi:/app/CompositeUi/var/cache
    networks:
      crv_prod_network:
        aliases:
          - php
    env_file:
      - ./.env

  nginx-prod:
    container_name: nginx-server-prod
    build:
      context: nginx/prod
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - app_data:/app:rw
      - ./volumes/log/prod/Nginx:/var/log/nginx
    depends_on:
      - app-prod

    networks:
      crv_prod_network:
        aliases:
          - nginx

volumes:
    app_data:
        driver: local
