FROM nginx

RUN apt-get update && \
    apt-get install -y vim

COPY conf/prod/nginx.conf /etc/nginx/nginx.conf
ADD sites-enabled/prod/ /etc/nginx/sites-enabled/

CMD ["nginx", "-g", "daemon off;"]
RUN usermod -u 1000 www-data
